# Generated by Django 4.0.5 on 2022-11-04 14:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('url_doc', models.TextField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('url_logo', models.TextField()),
                ('categories', models.ManyToManyField(related_name='posts', to='categories.category')),
            ],
        ),
    ]
