# Generated by Django 4.0.5 on 2022-11-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_alter_interaction_post_alter_interaction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='interaction',
            field=models.CharField(blank=True, choices=[('Like', 'Like'), ('Dislike', 'Dislike')], default='Like', max_length=30, null=True),
        ),
    ]
